# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import primenumber_pb2 as primenumber__pb2


class PrimeDecompositionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrimeNumber = channel.unary_stream(
                '/calculator.PrimeDecomposition/PrimeNumber',
                request_serializer=primenumber__pb2.PrimeRequest.SerializeToString,
                response_deserializer=primenumber__pb2.PrimeReply.FromString,
                )


class PrimeDecompositionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrimeNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimeDecompositionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrimeNumber': grpc.unary_stream_rpc_method_handler(
                    servicer.PrimeNumber,
                    request_deserializer=primenumber__pb2.PrimeRequest.FromString,
                    response_serializer=primenumber__pb2.PrimeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.PrimeDecomposition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrimeDecomposition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrimeNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/calculator.PrimeDecomposition/PrimeNumber',
            primenumber__pb2.PrimeRequest.SerializeToString,
            primenumber__pb2.PrimeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
